### ISSUE TITLE
The model selection JSON file is overwritten with defaults on re-start

### ISSUE THREAD

**Issue by galeone** [zurutech/ashpy#42]
Scenario:

- You're training a model and doing model selection
- You stop the train
- You re-start the train

The JSON file of the model selection is overwritten with default values, making you lost the previously (correctly stored) value.

**Comment by EmanueleGhelfi** [comment]
Probably the problem is here, we do not check existing values in the json file: https://github.com/zurutech/ashpy/blob/7dc0b4021d0ee3dd13272fd76e08fa30b041ae40/src/ashpy/metrics/metric.py#L117

I thought the training restart worked. Maybe we should add tests about restarting an existing training to avoid regressions on this side.
