### ISSUE TITLE
Dependency Updater

### ISSUE THREAD

**Issue by EmanueleGhelfi** [zurutech/ashpy#7]
Maybe we can setup a dependency updater like: https://github.com/pyupio/pyup

**Comment by galeone** [comment]
Personally, I don't really like the idea of a dependency updater like this one.
The reason is that I prefer to work with a set of dependencies I know to work well together without the hurry to update them (this only makes sense for security patches - but its Github itself that notify us if a dependency has a known security issue) and release a new version with updated dependencies only after having tested the package extensively.

**Comment by EmanueleGhelfi** [comment]
Ok, good point. Closing the issue.
